before_script:
   - git submodule sync
   - git submodule update --init
   - mkdir QuICC_builds
   - cd QuICC_builds

SerialShortCartesianBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Serial-Cartesian
      - cd Release-Serial-Cartesian
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial short_cartesian ${RUNNER_QUICC_PARAMAKE}

SerialLongCartesianBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Serial-Cartesian
      - cd Release-Serial-Cartesian
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial long_cartesian ${RUNNER_QUICC_PARAMAKE}

SerialShortCylindricalBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Serial-Cylindrical
      - cd Release-Serial-Cylindrical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial short_cylindrical ${RUNNER_QUICC_PARAMAKE}

SerialLongCylindricalBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Serial-Cylindrical
      - cd Release-Serial-Cylindrical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial long_cylindrical ${RUNNER_QUICC_PARAMAKE}

SerialShortSphericalBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Serial-Spherical
      - cd Release-Serial-Spherical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial short_spherical ${RUNNER_QUICC_PARAMAKE}

SerialLongSphericalBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Serial-Spherical
      - cd Release-Serial-Spherical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Serial long_spherical ${RUNNER_QUICC_PARAMAKE}

TubularShortCartesianBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Tubular-Cartesian
      - cd Release-Tubular-Cartesian
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular short_cartesian ${RUNNER_QUICC_PARAMAKE}

TubularLongCartesianBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Tubular-Cartesian
      - cd Release-Tubular-Cartesian
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular long_cartesian ${RUNNER_QUICC_PARAMAKE}

TubularShortCylindricalBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Tubular-Cylindrical
      - cd Release-Tubular-Cylindrical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular short_cylindrical ${RUNNER_QUICC_PARAMAKE}

TubularLongCylindricalBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Tubular-Cylindrical
      - cd Release-Tubular-Cylindrical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular long_cylindrical ${RUNNER_QUICC_PARAMAKE}

TubularShortSphericalBuild:
   stage: build
   except:
      - master
   script:
      - mkdir Release-Tubular-Spherical
      - cd Release-Tubular-Spherical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular short_spherical ${RUNNER_QUICC_PARAMAKE}

TubularLongSphericalBuild:
   stage: build
   only:
      - master
   script:
      - mkdir Release-Tubular-Spherical
      - cd Release-Tubular-Spherical
      - bash TestSuite/Bash/test_build.sh ${CI_PROJECT_DIR} ${RUNNER_QUICC_PLATFORM} Tubular long_spherical ${RUNNER_QUICC_PARAMAKE}
