before_script:
  - mkdir QuICC_builds
  - cd QuICC_builds
  
BoussinesqDynamoSphereStd:
  script:
    - mkdir -p BoussinesqDynamoSphereStd/Serial
    - cd BoussinesqDynamoSphereStd/Serial
    - cmake -DCMAKE_BUILD_TYPE=Release -DQUICC_PLATFORM=Lothlorien  ../../../ || true
    - cmake -DQUICC_BOUNDARYMETHOD=Tau -DQUICC_FFTPLAN=Medium -DQUICC_MEMORYUSAGE=High -DQUICC_MPIALGO=Serial -DQUICC_PYTHON=python34 -DQUICC_SMARTPTR=TR1 -DQUICC_SPLINALG=UmfPack -DQUICC_TIMESTEPPER=ImExRKCB2  ../../../ || true
    - cmake -DQUICC_TRANSGROUPER=Equation ../../../
    - make -j 4 BoussinesqDynamoSphereStdConfig
    - make -j 4 BoussinesqDynamoSphereStdState
    - make -j 4 BoussinesqDynamoSphereStdModel
    - make -j 4 BoussinesqDynamoSphereStdVisu