set(MHDSources
   BoundaryPart.cpp
   IConfigurationPart.cpp
   IoPart.cpp
   ParallelPart.cpp
   PhysicalPart.cpp
   RunPart.cpp
   StatisticsPart.cpp
   TimesteppingPart.cpp
   TruncationPart.cpp
)
