set(MHDSources
   BackwardConfigurator.cpp
   ForwardConfigurator.cpp
   ProjectorBranch.cpp
   ProjectorTree.cpp
   ProjectorTreeTools.cpp
   IntegratorBranch.cpp
   IntegratorTree.cpp
   IntegratorTreeTools.cpp
)

if(GEOMHDISCC_SPATIALSCHEME STREQUAL "TTT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "TFT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "TFF" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "FFF")
   list(APPEND MHDSources
      CartesianTransformSteps.cpp
      )
elseif(GEOMHDISCC_SPATIALSCHEME STREQUAL "AFT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "CFT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WFT")
   list(APPEND MHDSources
      CylindricalTransformSteps.cpp
      )
elseif(GEOMHDISCC_SPATIALSCHEME STREQUAL "SLF" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLF" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WFL")
   list(APPEND MHDSources
      SphericalTransformSteps.cpp
      )
endif(GEOMHDISCC_SPATIALSCHEME STREQUAL "TTT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "TFT" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "TFF" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "FFF")
