# Create list of sources for test case
set(MHDTestSources
   Exceptions/Exception.cpp
   Profiler/ProfilerBase.cpp
   Profiler/SerialProfiler.cpp
   Framework/FrameworkBase.cpp
   Framework/SerialFramework.cpp
   IoTools/Formatter.cpp
   Resolutions/Resolution.cpp
   Resolutions/CoreResolution.cpp
   Resolutions/SimulationResolution.cpp
   Resolutions/TransformResolution.cpp
   LoadSplitter/LoadSplitter.cpp
   LoadSplitter/Algorithms/SplittingTools.cpp
   LoadSplitter/Algorithms/SplittingDescription.cpp
   LoadSplitter/Algorithms/SplittingAlgorithm.cpp
   LoadSplitter/Algorithms/SerialSplitting.cpp
   SpatialSchemes/ISchemeCosts.cpp
   SpatialSchemes/ISpatialScheme.cpp
   SpatialSchemes/3D/IRegular3DScheme.cpp
   SpatialSchemes/3D/TFTScheme.cpp
   FastTransforms/FftSetup.cpp
   FastTransforms/FftwTools.cpp
   IoTools/VisualizeResolution.cpp
)
