set(MHDSources
)

if(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "SLFM" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR QUICC_SPATIALSCHEME STREQUAL "BLFM" OR QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM" OR QUICC_SPATIALSCHEME STREQUAL "WFT")
   list(APPEND MHDSources
      PolySetup.cpp
      PolynomialTools.cpp
      )
endif(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "SLFM" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR QUICC_SPATIALSCHEME STREQUAL "BLFM" OR QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM" OR QUICC_SPATIALSCHEME STREQUAL "WFT")

if(QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM")
   list(APPEND MHDSources
      ThreeTermRecurrence.cpp
      JacobiPolynomial.cpp
      WorlandPolynomial.cpp
      WorlandOperators.cpp
      SphereWorlandTransform.cpp
      )
endif(QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM")

if(QUICC_SPATIALSCHEME STREQUAL "WFT" )
   list(APPEND MHDSources
      ThreeTermRecurrence.cpp
      JacobiPolynomial.cpp
      WorlandPolynomial.cpp
      CylinderWorlandTransform.cpp
      )
endif(QUICC_SPATIALSCHEME STREQUAL "WFT")

if(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "SLFM" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR QUICC_SPATIALSCHEME STREQUAL "BLFM" OR QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM")
   list(APPEND MHDSources
      AssociatedLegendreTransform.cpp
      AssociatedLegendrePolynomial.cpp
      )
   if(QUICC_ALEGTRA STREQUAL "Fly")
      list(APPEND MHDSources
         AssociatedLegendreFlyTransform.cpp
      )
    endif(QUICC_ALEGTRA STREQUAL "Fly")
endif(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "SLFM" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR  QUICC_SPATIALSCHEME STREQUAL "BLFM" OR QUICC_SPATIALSCHEME STREQUAL "WLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFM")
