set(MHDSources
)

if(GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WFT")
   list(APPEND MHDSources 
      PolySetup.cpp
      PolynomialTools.cpp
      )
endif(GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WFT")

if(GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM")
   list(APPEND MHDSources 
      ThreeTermRecurrence.cpp
      JacobiPolynomial.cpp
      WorlandPolynomial.cpp
      SphereWorlandTransform.cpp
      )
endif(GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM")

if(GEOMHDISCC_SPATIALSCHEME STREQUAL "WFT" )
   list(APPEND MHDSources 
      ThreeTermRecurrence.cpp
      JacobiPolynomial.cpp
      WorlandPolynomial.cpp
      CylinderWorlandTransform.cpp
      )
endif(GEOMHDISCC_SPATIALSCHEME STREQUAL "WFT")

if(GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM")
   list(APPEND MHDSources 
      AssociatedLegendreTransform.cpp
      AssociatedLegendreFlyTransform.cpp
      AssociatedLegendrePolynomial.cpp
      )
endif(GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "SLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFL" OR  GEOMHDISCC_SPATIALSCHEME STREQUAL "BLFM" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFL" OR GEOMHDISCC_SPATIALSCHEME STREQUAL "WLFM")
