set(MHDModelSources
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGMeanHeat.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGfbx.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGfby.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGfbz.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGBy.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGBx.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGEmfx.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGEmfy.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGStreamfunction.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGPressure.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGVelocityZ.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGTransport.cpp
	${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqDynamo3DQGVorticityZ.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen2DTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/NusseltTags.cpp
   ${QUICC_SRC_DIR}/IoStats/AvgTags.cpp
   ${QUICC_SRC_DIR}/IoStats/Cartesian1DScalarAvgWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DNusseltZWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DStreamEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DMagneticEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
