set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Shell/Boussinesq/BoussinesqDynamoShellTransport.cpp
   ${QUICC_SRC_DIR}/Equations/Shell/Boussinesq/BoussinesqDynamoShellMomentum.cpp
   ${QUICC_SRC_DIR}/Equations/Shell/Boussinesq/BoussinesqDynamoShellInduction.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/EigenSHlTools.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/EigenSHlmTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/ShellScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/ShellTorPolEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/States/ShellExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/ShellExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/ShellExactVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/SphericalVerticalFieldVisualizer.cpp
)
