set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRBCylinderVCTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRBCylinderVCMomentum.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRBCylinderVCContinuity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationEigen1DTools.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CylinderExactStateIds.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CylinderExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CylinderExactVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
