set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqFPlane3DQGMeanHeat.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqFPlane3DQGStreamfunction.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqFPlane3DQGVelocityZ.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqFPlane3DQGTransport.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlane3DQG/Boussinesq/BoussinesqFPlane3DQGVorticityZ.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen2DTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/NusseltTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DNusseltZWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DStreamEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoStats/AvgTags.cpp
   ${QUICC_SRC_DIR}/IoStats/RmsTags.cpp
   ${QUICC_SRC_DIR}/IoStats/SkewTags.cpp
   ${QUICC_SRC_DIR}/IoStats/KurtTags.cpp
   ${QUICC_SRC_DIR}/IoStats/Cartesian1DScalarAvgWriter.cpp
   ${QUICC_SRC_DIR}/IoStats/Cartesian1DScalarRMSWriter.cpp
   ${QUICC_SRC_DIR}/IoStats/Cartesian1DScalarSkewWriter.cpp
   ${QUICC_SRC_DIR}/IoStats/Cartesian1DScalarKurtWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
