set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqAnnulusVCTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqAnnulusVCVelocityX.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqAnnulusVCVelocityY.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqAnnulusVCVelocityZ.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqAnnulusVCContinuity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationEigen1DTools.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/AnnulusExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
