set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlaneNHBGE/Boussinesq/BoussinesqFPlaneNHBGEMeanHeat.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlaneNHBGE/Boussinesq/BoussinesqFPlaneNHBGEStreamfunction.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlaneNHBGE/Boussinesq/BoussinesqFPlaneNHBGEVelocityZ.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlaneNHBGE/Boussinesq/BoussinesqFPlaneNHBGETransport.cpp
   ${QUICC_SRC_DIR}/Equations/Asymptotics/FPlaneNHBGE/Boussinesq/BoussinesqFPlaneNHBGEVorticityZ.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen2DTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/NusseltTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DNusseltZWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DStreamEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
