set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqRRBAnnulusVCTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqRRBAnnulusVCMomentum.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Annulus/Boussinesq/BoussinesqRRBAnnulusVCContinuity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationEigen1DTools.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/AnnulusExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
