set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRBCCylinderTransport.cpp
   ${QUICC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRBCCylinderMomentum.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen1DTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/CylinderScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/IoVariable/CylinderTorPolEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldTrivialVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/VectorFieldTrivialVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/NonlinearVectorFieldVisualizer.cpp
)
