set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Box/Boussinesq/BoussinesqRB3DBoxVCTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Box/Boussinesq/BoussinesqRB3DBoxVCMomentum.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Box/Boussinesq/BoussinesqRB3DBoxVCContinuity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationNoEigenTools.cpp
   ${GEOMHDISCC_SRC_DIR}/IoVariable/NusseltCubicWriter.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CartesianExactStateIds.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CartesianExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CartesianExactVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
