set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Sphere/Boussinesq/BoussinesqPrecessionDynamoSphereMomentum.cpp
   ${QUICC_SRC_DIR}/Equations/Sphere/Boussinesq/BoussinesqPrecessionDynamoSphereInduction.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/EigenSHlTools.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/EigenSHlmTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/SphereTorPolEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/States/SphereExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/SphereExactVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
