set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqCylinderTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqCylinderVelocity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationEigen1DTools.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CylinderExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/CylinderExactVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
