set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRRBCCylinderVCTransport.cpp
   ${QUICC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRRBCCylinderVCMomentum.cpp
   ${QUICC_SRC_DIR}/Equations/Cylinder/Boussinesq/BoussinesqRRBCCylinderVCContinuity.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen1DTools.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/CylinderExactVectorState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
