set(MHDModelSources
   ${GEOMHDISCC_SRC_DIR}/Equations/Sphere/Boussinesq/BoussinesqRTCSphereeTransport.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Sphere/Boussinesq/BoussinesqRTCSphereeVelocity.cpp
   ${GEOMHDISCC_SRC_DIR}/Equations/Tools/EquationEigenSHmTools.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/RandomVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/SphereExactStateIds.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/SphereExactScalarState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/States/SphereExactVectorState.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
   ${GEOMHDISCC_SRC_DIR}/Generator/Visualizers/VectorFieldVisualizer.cpp
)
