set(MHDPhysicalModels 
   AnelasticBetaSphGModel.hpp
   AnelasticFPlaneModel.hpp
   BoussinesqAnnulusModel.hpp
   BoussinesqBeta3DQGModel.hpp
   BoussinesqCylinderModel.hpp
   BoussinesqFPlane3DQGModel.hpp
   BoussinesqPerBetaCylGModel.hpp
   BoussinesqShellModel.hpp
   BoussinesqSphereModel.hpp
   RayleighBenardModel.hpp
   RotatingRBModel.hpp
   )

set(MHDTestModels 
   TestTTTModel.hpp
   TestTFTModel.hpp
   TestTFFModel.hpp
   TestFFFModel.hpp
   )
