set(MHDPhysicalModels 
   BoussinesqBeta3DQGModel.hpp
   BoussinesqBeta3DQGPerModel.hpp
   BoussinesqFPlane3DQGModel.hpp
   #BoussinesqRB1DBoxVCModel.hpp
   #BoussinesqRB2DBoxVCModel.hpp
   #BoussinesqRB3DBoxVCModel.hpp
   #BoussinesqRBAnnulusVCModel.hpp
   #BoussinesqRBCylinderVCModel.hpp
   #BoussinesqRRB1DBoxVCModel.hpp
   #BoussinesqRRB2DBoxVCModel.hpp
   #BoussinesqRRB3DBoxVCModel.hpp
   #BoussinesqRRBAnnulusVCModel.hpp
   #BoussinesqRRBCylinderVCModel.hpp
   #BoussinesqShellModel.hpp
   #BoussinesqSphereModel.hpp
   )

set(MHDTestModels 
   TestTTTModel.hpp
   TestTFTModel.hpp
   TestTFFModel.hpp
   TestFFFModel.hpp
   )
