set(MHDPhysicalModels 
   # 2D models
   BoussinesqRBCPlane2DVCModel.hpp
   BoussinesqRBCSquareVCModel.hpp
   BoussinesqRBCSquareSModel.hpp
   # 3D models
   BoussinesqBeta3DQGModel.hpp
   BoussinesqBeta3DQGPerModel.hpp
   BoussinesqFPlane3DQGModel.hpp
   BoussinesqFPlaneNHBGEModel.hpp
   BoussinesqTiltedFPlane3DQGModel.hpp
   BoussinesqNoTiltedFPlane3DQGModel.hpp
   BoussinesqRBCDuctVCModel.hpp
   BoussinesqRBCPlaneVCModel.hpp
   BoussinesqRBCBoxVCModel.hpp
   BoussinesqRBCAnnulusVCModel.hpp
   BoussinesqRBCCylinderVCModel.hpp
   BoussinesqRBCCylinderModel.hpp
   BoussinesqRRBCDuctVCModel.hpp
   BoussinesqRRBCPlaneModel.hpp
   BoussinesqRRBCPlaneMeanModel.hpp
   BoussinesqRRBCPlaneDMeanModel.hpp
   BoussinesqRRBCPlaneVCModel.hpp
   BoussinesqRRBCBoxVCModel.hpp
   BoussinesqRRBCAnnulusVCModel.hpp
   BoussinesqRRBCCylinderModel.hpp
   BoussinesqRRBCCylinderVCModel.hpp
   BoussinesqTCShellModel.hpp
   BoussinesqTCShellStdModel.hpp
   BoussinesqRTCShellModel.hpp
   BoussinesqRTCShellStdModel.hpp
   BoussinesqDynamoShellModel.hpp
   BoussinesqDynamoShellStdModel.hpp
   BoussinesqTCSphereModel.hpp
   BoussinesqTCSphereStdModel.hpp
   BoussinesqRTCSphereModel.hpp
   BoussinesqRTCSphereStdModel.hpp
   BoussinesqDynamoSphereModel.hpp
   BoussinesqDynamoSphereStdModel.hpp
   BoussinesqCouetteShellStdModel.hpp
   BoussinesqDynamoCouetteShellStdModel.hpp
   )

set(MHDTestModels 
   TimestepperTFFTest.hpp
   )
