set(MHDModelSources
   ${QUICC_SRC_DIR}/Equations/Tests/TimestepperTFFScalar.cpp
   ${QUICC_SRC_DIR}/Equations/Tests/TimestepperTFFTimeAvgScalar.cpp
   ${QUICC_SRC_DIR}/Equations/Tools/Eigen2DTools.cpp
   ${QUICC_SRC_DIR}/IoVariable/EnergyTags.cpp
   ${QUICC_SRC_DIR}/IoVariable/Cartesian1DScalarEnergyWriter.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactStateIds.cpp
   ${QUICC_SRC_DIR}/Generator/States/CartesianExactScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/States/RandomScalarState.cpp
   ${QUICC_SRC_DIR}/Generator/Visualizers/ScalarFieldVisualizer.cpp
)
