set(MHDSources
   FftSetup.cpp
   FftwLibrary.cpp
   FftwTools.cpp
   FftwTransform.cpp
   ChebyshevFftwTransform.cpp
   SphereChebyshevFftwTransform.cpp
   ShellChebyshevFftwTransform.cpp
   CylinderChebyshevFftwTransform.cpp
   AnnulusChebyshevFftwTransform.cpp
)
