set(MHDSources
   FftSetup.cpp
   FftwLibrary.cpp
   FftwTools.cpp
   FftwTransform.cpp
   ChebyshevFftwTransform.cpp
   SphericalChebyshevFftwTransform.cpp
   CylindricalChebyshevFftwTransform.cpp
)
