set(MHDSources
   NoIndexConv.cpp
   PMIndexConv.cpp
)

if(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFL")
   list(APPEND MHDSources
      SHlIndexConv.cpp
      )
elseif(QUICC_SPATIALSCHEME STREQUAL "SLFM" OR QUICC_SPATIALSCHEME STREQUAL "BLFM" OR QUICC_SPATIALSCHEME STREQUAL "WLFM")
   list(APPEND MHDSources
      SHmIndexConv.cpp
      )
endif(QUICC_SPATIALSCHEME STREQUAL "SLFL" OR QUICC_SPATIALSCHEME STREQUAL "BLFL" OR QUICC_SPATIALSCHEME STREQUAL "WLFL")

if(QUICC_MPI)
   list(APPEND MHDSources
      MpiConverterTools.cpp
   )
endif(QUICC_MPI)
